export const colorsType = [
  "nn-silver",
  "nn-royal-purple",
  "nn-persian-red",
  "nn-denim",
  "nn-gold-tips",
  "nn-shamrock",
  "nn-cod-grey",
  "nn-gravel",
  "nn-emerald",
  "nn-burn-orange",
  "nn-razzmatazz",
  "nn-desert",
  "nn-charcoal",
  "nn-golden-brown",
  "nn-sepia",
  "nn-alizarin",
  "nn-rust",
  "nn-blush",
  "nn-fire-brick",
  "nn-sunglow",
  "nn-milk-punch",
  "nn-yukon-gold",
  "nn-green-pea",
  "nn-laurel",
  "nn-elf-green",
  "nn-lake",
  "nn-cobalt-blue",
  "nn-mariner",
  "nn-fuchsia",
  "nn-blue-violet",
  "nn-purple-heart",
];

export const directionsType = [
  "nn-up",
  "nn-down",
  "nn-left",
  "nn-right",
];

export const containerSizesType = [
  "nn-sz400",
  "nn-sz500",
  "nn-sz600",
  "nn-sz900",
  "nn-sz1450",
]